### ISSUE TITLE
As an unregistered user, I want to be able to register as a user with my chosen credentials (username, email, password, none empty) to have full access to all features and services, available to registered users

### ISSUE THREAD

**Issue by arminveres** [sopra-fs22-group-08/server#1]
* Acceptance Criteria:
  * Upon successful user registration the user receives an email confirmation and
is logged in
  * Upon failure, an error is displayed and the user is redirected back to the
register screen.
    * A register Error can be that a username/email is already taken
  * The creation date of a user is saved to the database record.
  * Logged-in users can log out and log back into their registered profile
* Priority: Critical
* Author: Armin Veres
* Estimate: 6h

Task Lists
- [x] sopra-fs22-group-08/client#11
- [x] sopra-fs22-group-08/server#30
- [x] sopra-fs22-group-08/client#12
- [x] sopra-fs22-group-08/server#31
- [x] sopra-fs22-group-08/server#16

**Comment by arminveres** [comment]
All tickets implemented.
