### ISSUE TITLE
As a logged-in user, I want to be able to sell my public card decks to other users.

### ISSUE THREAD

**Issue by arminveres** [sopra-fs22-group-08/server#10]
* Acceptance criteria:
  * By clicking on a “add Price” button the user is able to add a price for a public
card deck.
  * By adding a price the other users have to pay for using the card deck.
  * The webapp creator will take a fee and the rest goes to the creator of the card
deck.
* Priority: low
* Author: Nico Reding
* Estimate 10h

- [ ] sopra-fs22-group-08/client#16
- [ ] sopra-fs22-group-08/server#45
- [ ] sopra-fs22-group-08/client#17
- [ ] sopra-fs22-group-08/server#47
