### ISSUE TITLE
add logic for multiplayer/networking (backend)

### ISSUE THREAD

**Issue by arminveres** [sopra-fs22-group-08/server#49]
- [x] sopra-fs22-group-08/server#95
- [x] add tests for Duel (resolved in #114 )
- [x] #108
- [x] sopra-fs22-group-08/server#97
- [x] sopra-fs22-group-08/server#98
- [ ] further implementation pending ...
