### ISSUE TITLE
As a logged-in user, I want to create a deck and add flashcards to which the user can write Information on.

### ISSUE THREAD

**Issue by arminveres** [sopra-fs22-group-08/server#5]
* Acceptance Criteria:
  * By clicking on a “create deck” button the user is able to create a new deck for
flash cards.
  * By clicking on an add button the user can add flashcards to the created deck.
  * The user can write content for the front and back of the flash card into a input field.
  * (The cards can be of the Format Open Questions or Multiple Choice)
  * The created decks and flashcards are saved, such that the user can use them
when logging back in.
* Priority: critical
* Author: Robert Hemengül
* Estimate: 20h

**Backend**
- [x] sopra-fs22-group-08/server#36
- [x] sopra-fs22-group-08/server#73

**Frontend**
- [x] sopra-fs22-group-08/client#6
- [x] sopra-fs22-group-08/client#49
- [x] sopra-fs22-group-08/client#108
