### ISSUE TITLE
As a logged-in user, I want to be able to edit and change content of the flash cards and decks.

### ISSUE THREAD

**Issue by arminveres** [sopra-fs22-group-08/server#7]
* Acceptance criteria:
  * By clicking on the delete button the user can delete any card from the deck.
  * By clicking the add button the user can add a card to the deck.
  * By clicking the edit button the user can edit the content of any card.
  * The user can click on a button and change the name of the deck.
  * I can click into the search bar in the deck overview to search through my decks.
* Priority: critical
* Author: Robert Hemengül
* Estimate 12h

**Backend**
- [x] sopra-fs22-group-08/server#37 
- [x] sopra-fs22-group-08/server#89
- [x] sopra-fs22-group-08/server#37 

**Frontend**
- [x] sopra-fs22-group-08/client#9
- [x] sopra-fs22-group-08/client#8 
- [x] sopra-fs22-group-08/client#7 
- [x] sopra-fs22-group-08/client#39
- [x] sopra-fs22-group-08/client#107
- [x] sopra-fs22-group-08/client#106
