### ISSUE TITLE
As a logged-in user, I want to be able to search public decks, in order to play/review them.

### ISSUE THREAD

**Issue by arminveres** [sopra-fs22-group-08/server#8]
* Acceptance criteria:
  * By clicking on the Store button in the burger menu I can get to the public deck overview.
  * By clicking into the search field, I can search for public decks by name.
  * The decks are sorted into different categories.
  * By clicking on the card decks button the user can view a list of all card decks.
* Priority: critical
* Author: Nico Reding
* Estimate 8h

**Backend**
- [x] sopra-fs22-group-08/server#28
- [x] sopra-fs22-group-08/server#41

**Frontend**
- [x] sopra-fs22-group-08/client#40
- [x] sopra-fs22-group-08/client#8 
- [x] sopra-fs22-group-08/client#10
- [x] sopra-fs22-group-08/client#14
