### ISSUE TITLE
As a logged in user, I want to be able to work through the Multiple Choice flashcard decks and test my knowledge.

### ISSUE THREAD

**Issue by arminveres** [sopra-fs22-group-08/server#80]
* Acceptance Criteria:
  * There is a button to start the process of going through the cards.
  * Each card shows a question and four possible answers.
  * The four shown answers are in random order.
  * I can choose one of four answers.
  * By clicking a "check answer" button, the given answer is compared to the correct one and displayed to the user.
  * The order in which the cards are shown is random.
* Priority: critical
* Author: Robert Hemengül
* Estimate: 20h

**Backend**
- [x] sopra-fs22-group-08/server#81
- [x] sopra-fs22-group-08/server#82
- [x] #73 

**Frontend**
- [x] sopra-fs22-group-08/client#36
- [x] sopra-fs22-group-08/client#37
